Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -9,27 +9,27 @@ on:
       - "*"
 
 jobs:
-  verify_version:
-    name: Verify version matches release
-    runs-on: ubuntu-24.04
-    strategy:
-      matrix:
-        os: [ubuntu-24.04, macos-14, windows-2022]
-        sdk: [3.0.0]
-    steps:
-      - uses: actions/checkout@v4
-      - uses: subosito/flutter-action@v2
-        with:
-          flutter-version: ${{ env.FLUTTER_OVERRIDE || vars.FLUTTER_VERSION }}
-      - name: Verify release version
-        run: |
-          flutter pub get
-          dart tool/verify_release_version.dart ${{ github.ref_name }}
-        working-directory: packages/isar_community
+#  verify_version:
+#    name: Verify version matches release
+#    runs-on: ubuntu-24.04
+#    strategy:
+#      matrix:
+#        os: [ubuntu-24.04, macos-14, windows-2022]
+#        sdk: [3.0.0]
+#    steps:
+#      - uses: actions/checkout@v4
+#      - uses: subosito/flutter-action@v2
+#        with:
+#          flutter-version: ${{ env.FLUTTER_OVERRIDE || vars.FLUTTER_VERSION }}
+#      - name: Verify release version
+#        run: |
+#          flutter pub get
+#          dart tool/verify_release_version.dart ${{ github.ref_name }}
+#        working-directory: packages/isar_community
 
   build_binaries:
     name: Build Binaries
-    needs: verify_version
+    #needs: verify_version
     strategy:
       fail-fast: false
       matrix:
@@ -88,66 +88,66 @@ jobs:
           asset_name: ${{ matrix.artifact_name }}
           tag: ${{ github.ref }}
 
-  testlab:
-    needs: build_binaries
-    uses: ./.github/workflows/testlab.yaml
-    secrets: inherit
+  #testlab:
+  #  needs: build_binaries
+  #  uses: ./.github/workflows/testlab.yaml
+  #  secrets: inherit
 
-  build_inspector:
-    name: Build Inspector
-    needs: build_binaries
-    runs-on: ubuntu-24.04
-    steps:
-      - uses: actions/checkout@v4
-      - uses: subosito/flutter-action@v2
-        with:
-          flutter-version: ${{ env.FLUTTER_OVERRIDE || vars.FLUTTER_VERSION }}
-      - name: Build
-        run: flutter build web --base-href /${{ github.ref_name }}/
-        working-directory: packages/isar_community_inspector
-      - name: Deploy to GitHub Pages
-        uses: JamesIves/github-pages-deploy-action@v4
-        with:
-          folder: packages/isar_community_inspector/build/web
-          repository-name: ${{ vars.REPO_INSPECTOR }}
-          token: ${{ secrets.DEPLOY_TOKEN }}
-          target-folder: ${{ github.ref_name }}
-          clean: false
+  #build_inspector:
+  #  name: Build Inspector
+  #  needs: build_binaries
+  #  runs-on: ubuntu-24.04
+  #  steps:
+  #    - uses: actions/checkout@v4
+  #    - uses: subosito/flutter-action@v2
+  #      with:
+  #        flutter-version: ${{ env.FLUTTER_OVERRIDE || vars.FLUTTER_VERSION }}
+  #    - name: Build
+  #      run: flutter build web --base-href /${{ github.ref_name }}/
+  #      working-directory: packages/isar_community_inspector
+  #    - name: Deploy to GitHub Pages
+  #      uses: JamesIves/github-pages-deploy-action@v4
+  #      with:
+  #        folder: packages/isar_community_inspector/build/web
+  #        repository-name: ${{ vars.REPO_INSPECTOR }}
+  #        token: ${{ secrets.DEPLOY_TOKEN }}
+  #        target-folder: ${{ github.ref_name }}
+  #        clean: false
 
-  upload_to_repo:
-    needs: build_binaries
-    runs-on: ubuntu-24.04
-    steps:
-      - name: Download all artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: binaries/
-      - name: List contents of downloaded artifacts
-        run: |
-          echo "Listing contents of all downloaded artifacts..."
-          ls -Rlh binaries/
-          echo "Listing complete."
-      - name: Setup Git and clone target repository
-        run: |
-          git config --global user.email "vicente.russo@gmail.com"
-          git config --global user.name "GitHub Actions"
-          git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_BINARIES }}.git repo
-          cd repo
-          git checkout main || git checkout -b main
-        env:
-          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
-      - name: Copy binaries to repository and push
-        run: |
-          cd repo
-          ISAR_VERSION=$(echo "${{ github.ref_name }}" | sed 's/refs\/tags\///')
-          echo "Deploying binaries to version: $ISAR_VERSION"
-          mkdir -p "$ISAR_VERSION"
-          cp ../binaries/**/* "$ISAR_VERSION"
-          git add .
-          git commit -m "Deploy binaries for version $ISAR_VERSION" || echo "No changes to commit"
-          git push https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_BINARIES }}.git main
-        env:
-          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
+  #upload_to_repo:
+  #  needs: build_binaries
+  #  runs-on: ubuntu-24.04
+  #  steps:
+  #    - name: Download all artifacts
+  #      uses: actions/download-artifact@v4
+  #      with:
+  #        path: binaries/
+  #    - name: List contents of downloaded artifacts
+  #      run: |
+  #        echo "Listing contents of all downloaded artifacts..."
+  #        ls -Rlh binaries/
+  #        echo "Listing complete."
+  #    - name: Setup Git and clone target repository
+  #      run: |
+  #        git config --global user.email "vicente.russo@gmail.com"
+  #        git config --global user.name "GitHub Actions"
+  #        git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_BINARIES }}.git repo
+  #        cd repo
+  #        git checkout main || git checkout -b main
+  #      env:
+  #        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
+  #    - name: Copy binaries to repository and push
+  #      run: |
+  #        cd repo
+  #        ISAR_VERSION=$(echo "${{ github.ref_name }}" | sed 's/refs\/tags\///')
+  #        echo "Deploying binaries to version: $ISAR_VERSION"
+  #        mkdir -p "$ISAR_VERSION"
+  #        cp ../binaries/**/* "$ISAR_VERSION"
+  #        git add .
+  #        git commit -m "Deploy binaries for version $ISAR_VERSION" || echo "No changes to commit"
+  #        git push https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_BINARIES }}.git main
+  #      env:
+  #        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
 
   # publish:
   #   name: Publish
@@ -175,56 +175,56 @@ jobs:
   #       run: dart pub publish --force
   #       working-directory: packages/isar_community_flutter_libs
 
-  cleanup_on_failure:
-    name: Cleanup Release on Failure
-    runs-on: ubuntu-24.04
-    needs: [build_binaries, testlab, build_inspector, upload_to_repo]
-    if: always() && contains(needs.*.result, 'failure')
-    permissions:
-      contents: write
-    steps:
-      - uses: actions/checkout@v4
-      - name: Delete release on failure
-        run: |
-          echo "One or more jobs failed. Deleting release ${{ github.ref_name }}"
-          gh release delete ${{ github.ref_name }} --yes || echo "Release not found or already deleted"
+  #cleanup_on_failure:
+  #  name: Cleanup Release on Failure
+  #  runs-on: ubuntu-24.04
+  #  needs: [build_binaries, testlab, build_inspector, upload_to_repo]
+  #  if: always() && contains(needs.*.result, 'failure')
+  #  permissions:
+  #    contents: write
+  #  steps:
+  #    - uses: actions/checkout@v4
+  #    - name: Delete release on failure
+  #      run: |
+  #        echo "One or more jobs failed. Deleting release ${{ github.ref_name }}"
+  #        gh release delete ${{ github.ref_name }} --yes || echo "Release not found or already deleted"
+  #      env:
+  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #    - name: Revert Inspector deployment
+  #      run: |
+  #        echo "Reverting Inspector deployment for ${{ github.ref_name }}"
+  #        git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_INSPECTOR }}.git inspector_repo
+  #        cd inspector_repo
+  #        git checkout gh-pages || echo "gh-pages branch not found"
+  #        if [ -d "${{ github.ref_name }}" ]; then
+  #          rm -rf "${{ github.ref_name }}"
+  #          git add .
+  #          git config user.email "vicente.russo@gmail.com"
+  #          git config user.name "GitHub Actions"
+  #          git commit -m "Revert inspector deployment for failed release ${{ github.ref_name }}" || echo "No changes to commit"
+  #          git push origin gh-pages
+  #          echo "Inspector deployment reverted"
+  #        else
+  #          echo "Inspector folder ${{ github.ref_name }} not found, nothing to revert"
+  #       fi
+  #      env:
+  #        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
+  #    - name: Revert binaries deployment
+  #      run: |
+  #        echo "Reverting binaries deployment for ${{ github.ref_name }}"
+  #        git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_BINARIES }}.git binaries_repo
+  #        cd binaries_repo
+  #        git checkout main || git checkout -b main
+  #        if [ -d "${{ github.ref_name }}" ]; then
+  #          rm -rf "${{ github.ref_name }}"
+  #          git add .
+  #          git config user.email "vicente.russo@gmail.com"
+  #          git config user.name "GitHub Actions"
+  #          git commit -m "Revert binaries for failed release ${{ github.ref_name }}" || echo "No changes to commit"
+  #          git push origin main
+  #          echo "Binaries deployment reverted"
+  #        else
+  #          echo "Binaries folder ${{ github.ref_name }} not found, nothing to revert"
+  #        fi
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Revert Inspector deployment
-        run: |
-          echo "Reverting Inspector deployment for ${{ github.ref_name }}"
-          git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_INSPECTOR }}.git inspector_repo
-          cd inspector_repo
-          git checkout gh-pages || echo "gh-pages branch not found"
-          if [ -d "${{ github.ref_name }}" ]; then
-            rm -rf "${{ github.ref_name }}"
-            git add .
-            git config user.email "vicente.russo@gmail.com"
-            git config user.name "GitHub Actions"
-            git commit -m "Revert inspector deployment for failed release ${{ github.ref_name }}" || echo "No changes to commit"
-            git push origin gh-pages
-            echo "Inspector deployment reverted"
-          else
-            echo "Inspector folder ${{ github.ref_name }} not found, nothing to revert"
-          fi
-        env:
-          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
-      - name: Revert binaries deployment
-        run: |
-          echo "Reverting binaries deployment for ${{ github.ref_name }}"
-          git clone https://x-access-token:${DEPLOY_TOKEN}@github.com/${{ vars.REPO_BINARIES }}.git binaries_repo
-          cd binaries_repo
-          git checkout main || git checkout -b main
-          if [ -d "${{ github.ref_name }}" ]; then
-            rm -rf "${{ github.ref_name }}"
-            git add .
-            git config user.email "vicente.russo@gmail.com"
-            git config user.name "GitHub Actions"
-            git commit -m "Revert binaries for failed release ${{ github.ref_name }}" || echo "No changes to commit"
-            git push origin main
-            echo "Binaries deployment reverted"
-          else
-            echo "Binaries folder ${{ github.ref_name }} not found, nothing to revert"
-          fi
-        env:
-          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
+          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}#
